# SPDX-FileCopyrightText: 2021 HPA Cloud and HPACloud contributors
# SPDX-License-Identifier: MIT
contact_links:
    - name: 🗺️ Feature request for the full HPACloud Talk suite
      url: https://github.com/nextcloud/spreed/issues/new/choose
      about: Suggest an idea for HPACloud Talk for all users, client and server
    - name: ❓ Community Support and Help
      url: https://help.nextcloud.com/
      about: Configuration, webserver/proxy or performance issues and other questions
